version: "3.8"

services:
  database:
    image: public.ecr.aws/docker/library/mysql:latest
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: "pass1234"
      MYSQL_PASSWORD: "pass1234"

  test:
    image: public.ecr.aws/docker/library/node:16-alpine
    working_dir: /app
    volumes:
      - ${PWD}:/app
    environment:
      - database=database
    command: sh -c "yarn && yarn test:ci"
    depends_on:
      - database
