version: "3.9"

services:
  db:
    container_name: node_template
    image: public.ecr.aws/docker/library/mysql:latest
    platform: linux/x86_64
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "pass1234"
      MYSQL_PASSWORD: "pass1234"
      MYSQL_DATABASE: "node_template"
