FROM public.ecr.aws/docker/library/node:16-alpine
WORKDIR /app

RUN yarn init -y
# TODO: trocar para prisma
RUN yarn add knex
RUN yarn add -D typescript @types/node

COPY ./knexfile.ts .
COPY ./migrations ./

CMD ["yarn", "knex", "migrate:latest"]
